#!/bin/sh /etc/rc.common

START=99

start() {
    logger "Starting the simonman"

    # Activate virtual environment
    venv_path='/root/cloud'

    if [ -d "$venv_path" ]; then
        if [ -f "$venv_path/bin/activate" ]; then
            . "$venv_path/bin/activate"
        else
            logger "Activate script not found in virtual environment."
            exit 1
        fi
    else
        logger "Virtual environment not found at: $venv_path"
        exit 1
    fi
    logger "Activate script success"

    # Run the Python script
    python /root/NDS/app.py
}

stop() {
    logger "Stopping the simonman"
    # Add stop actions if necessary
    pkill -f "/root/NDS/app.py"
}

restart() {
    logger "Restarting the simonman"
    stop
    sleep 1
    start
}
